variable "service_name" {}
variable "image" {}
variable "environment" {}
variable "cluster" {}
variable "cluster_id" {}
variable "aws_region" {}
variable "log_group_prefix" {}
variable "app_port" {}
variable "ecs_task_role_arn" {}
variable "ecs_target_group_arn" {}
//variable "ecs_service_role_arn" {}
variable "registry_arn" {}
variable "virtual_node_name" {}
variable "mesh_name" {}
variable "private_subnet_id" {}
variable "private_sg_id" {}