apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deploy
  labels:
    app: service-a-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
        version: v1
    spec:
      containers:
      - image: sample-app:a
        ports:
        - containerPort: 8000
        name: service-a

---

apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    run: service-a
spec:
  type: NodePort
  ports:
    - port: 8000
      name: http
  selector:
    app: service-a

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deploy
  labels:
    app: service-b-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        version: v1
    spec:
      containers:
      - image: sample-app:b
        ports:
        - containerPort: 8000
        name: service-b

---

apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    run: service-b
spec:
  ports:
    - port: 8000
      name: http
  selector:
    app: service-b

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c-deploy
  labels:
    app: service-c-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
        version: v1
    spec:
      containers:
      - image: sample-app:c
        ports:
        - containerPort: 8000
        name: service-c

---

apiVersion: v1
kind: Service
metadata:
  name: service-c
  labels:
    run: service-c
spec:
  ports:
    - port: 8000
      name: http
  selector:
    app: service-c

---